/* This file was generated by SableCC (http://www.sablecc.org/). */

package LinguaJet.lexer;

import java.io.*;
import java.util.*;
import LinguaJet.node.*;

public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private PushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    protected void filter() throws LexerException, IOException
    {
    }

    public Lexer(PushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(token == null)
        {
            token = getToken();
            filter();
        }

        return token;
    }

    public Token next() throws LexerException, IOException
    {
        while(token == null)
        {
            token = getToken();
            filter();
        }

        Token result = token;
        token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = pos;
        int start_line = line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        int[][][] gotoTable = this.gotoTable[state.id()];
        int[] accept = this.accept[state.id()];
        text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(cr)
                    {
                        cr = false;
                    }
                    else
                    {
                        line++;
                        pos = 0;
                    }
                    break;
                case 13:
                    line++;
                    pos = 0;
                    cr = true;
                    break;
                default:
                    pos++;
                    cr = false;
                    break;
                };

                text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        int middle = (low + high) / 2;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = text.length();
                    accept_pos = pos;
                    accept_line = line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            Token token = new1(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            Token token = new2(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            Token token = new3(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            Token token = new4(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            Token token = new5(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            Token token = new6(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            Token token = new7(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            Token token = new8(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            Token token = new9(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            Token token = new10(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            Token token = new11(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            Token token = new12(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            Token token = new13(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            Token token = new14(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            Token token = new16(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            Token token = new29(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            Token token = new30(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            Token token = new31(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(text.length() > 0)
                    {
                        throw new LexerException(
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + text);
                    }
                    else
                    {
                        EOF token = new EOF(
                            start_line + 1,
                            start_pos + 1);
                        return token;
                    }
                }
            }
        }
    }

    Token new0(String text, int line, int pos) { return new TComment1(text, line, pos); }
    Token new1(String text, int line, int pos) { return new TComment2(text, line, pos); }
    Token new2(String text, int line, int pos) { return new TSpace(text, line, pos); }
    Token new3(String text, int line, int pos) { return new TClas(text, line, pos); }
    Token new4(String text, int line, int pos) { return new TPublic(text, line, pos); }
    Token new5(String text, int line, int pos) { return new TStatic(text, line, pos); }
    Token new6(String text, int line, int pos) { return new TVoid(text, line, pos); }
    Token new7(String text, int line, int pos) { return new TMain(text, line, pos); }
    Token new8(String text, int line, int pos) { return new TString(text, line, pos); }
    Token new9(String text, int line, int pos) { return new TInt(text, line, pos); }
    Token new10(String text, int line, int pos) { return new TFloat(text, line, pos); }
    Token new11(String text, int line, int pos) { return new TFor(text, line, pos); }
    Token new12(String text, int line, int pos) { return new TWhile(text, line, pos); }
    Token new13(String text, int line, int pos) { return new TIf(text, line, pos); }
    Token new14(String text, int line, int pos) { return new TElse(text, line, pos); }
    Token new15(int line, int pos) { return new TAssign(line, pos); }
    Token new16(String text, int line, int pos) { return new TCompare(text, line, pos); }
    Token new17(int line, int pos) { return new TPlus(line, pos); }
    Token new18(int line, int pos) { return new TMinus(line, pos); }
    Token new19(int line, int pos) { return new TMult(line, pos); }
    Token new20(int line, int pos) { return new TDiv(line, pos); }
    Token new21(int line, int pos) { return new TLPar(line, pos); }
    Token new22(int line, int pos) { return new TRPar(line, pos); }
    Token new23(int line, int pos) { return new TLBrace(line, pos); }
    Token new24(int line, int pos) { return new TRBrace(line, pos); }
    Token new25(int line, int pos) { return new TLBracket(line, pos); }
    Token new26(int line, int pos) { return new TRBracket(line, pos); }
    Token new27(int line, int pos) { return new TComma(line, pos); }
    Token new28(int line, int pos) { return new TSemi(line, pos); }
    Token new29(String text, int line, int pos) { return new TIdentifier(text, line, pos); }
    Token new30(String text, int line, int pos) { return new TNumber(text, line, pos); }
    Token new31(String text, int line, int pos) { return new TMisc(text, line, pos); }

    private int getChar() throws IOException
    {
        if(eof)
        {
            return -1;
        }

        int result = in.read();

        if(result == -1)
        {
            eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            eof = false;

            in.unread(text.charAt(i));
        }
    }

    protected void unread(Token token) throws IOException
    {
        String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            eof = false;

            in.unread(text.charAt(i));
        }

        pos = token.getPos() - 1;
        line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{0, 8, 1}, {9, 9, 2}, {10, 10, 3}, {11, 12, 1}, {13, 13, 3}, {14, 31, 1}, {32, 32, 4}, {33, 33, 5}, {34, 39, 1}, {40, 40, 6}, {41, 41, 7}, {42, 42, 8}, {43, 43, 9}, {44, 44, 10}, {45, 45, 11}, {46, 46, 12}, {47, 47, 13}, {48, 57, 14}, {58, 58, 1}, {59, 59, 15}, {60, 60, 16}, {61, 61, 17}, {62, 62, 18}, {63, 64, 1}, {65, 82, 19}, {83, 83, 20}, {84, 90, 19}, {91, 91, 21}, {92, 92, 1}, {93, 93, 22}, {94, 96, 1}, {97, 97, 23}, {98, 98, 24}, {99, 99, 25}, {100, 100, 26}, {101, 101, 27}, {102, 102, 28}, {103, 105, 26}, {106, 106, 29}, {107, 107, 30}, {108, 108, 31}, {109, 109, 32}, {110, 111, 26}, {112, 112, 33}, {113, 113, 26}, {114, 114, 34}, {115, 115, 35}, {116, 116, 36}, {117, 117, 37}, {118, 118, 38}, {119, 120, 26}, {121, 121, 39}, {122, 122, 26}, {123, 123, 40}, {124, 124, 1}, {125, 125, 41}, {126, 65535, 1}, },
            {},
            {},
            {},
            {},
            {{61, 61, 42}, },
            {},
            {},
            {},
            {},
            {},
            {},
            {{48, 57, 43}, },
            {{42, 42, 44}, {47, 47, 45}, },
            {{46, 46, 46}, {48, 57, 47}, {69, 69, 48}, {101, 101, 48}, },
            {},
            {{61, 61, 49}, },
            {{61, 61, 50}, },
            {{61, 61, 51}, },
            {{48, 57, 52}, {65, 90, 53}, {95, 95, 54}, {97, 122, 55}, },
            {{48, 95, -21}, {97, 115, 55}, {116, 116, 56}, {117, 122, 55}, },
            {},
            {},
            {{48, 95, -21}, {97, 109, 55}, {110, 110, 57}, {111, 122, 55}, },
            {{48, 95, -21}, {97, 104, 55}, {105, 105, 58}, {106, 122, 55}, },
            {{48, 95, -21}, {97, 107, 55}, {108, 108, 59}, {109, 122, 55}, },
            {{48, 122, -21}, },
            {{48, 109, -25}, {110, 110, 60}, {111, 122, 55}, },
            {{48, 107, -27}, {108, 108, 61}, {109, 122, 55}, },
            {{48, 95, -21}, {97, 97, 62}, {98, 104, 55}, {105, 105, 63}, {106, 122, 55}, },
            {{48, 95, -21}, {97, 100, 55}, {101, 101, 64}, {102, 110, 55}, {111, 111, 65}, {112, 122, 55}, },
            {{48, 95, -21}, {97, 97, 66}, {98, 122, 55}, },
            {{48, 95, -21}, {97, 116, 55}, {117, 117, 67}, {118, 122, 55}, },
            {{48, 95, -21}, {97, 110, 55}, {111, 111, 68}, {112, 113, 55}, {114, 114, 69}, {115, 116, 55}, {117, 117, 70}, {118, 122, 55}, },
            {{48, 100, -32}, {101, 101, 71}, {102, 122, 55}, },
            {{48, 95, -21}, {97, 97, 72}, {98, 100, 55}, {101, 101, 73}, {102, 104, 55}, {105, 105, 74}, {106, 115, 55}, {116, 116, 75}, {117, 122, 55}, },
            {{48, 95, -21}, {97, 97, 76}, {98, 100, 55}, {101, 101, 77}, {102, 122, 55}, },
            {{48, 109, -25}, {110, 110, 78}, {111, 115, 55}, {116, 116, 79}, {117, 122, 55}, },
            {{48, 95, -21}, {97, 97, 80}, {98, 104, 55}, {105, 105, 81}, {106, 122, 55}, },
            {{48, 95, -21}, {97, 97, 82}, {98, 122, 55}, },
            {},
            {},
            {},
            {{48, 57, 43}, {69, 101, -16}, },
            {{0, 41, 83}, {42, 42, 84}, {43, 65535, 83}, },
            {{0, 9, 85}, {10, 10, 86}, {11, 12, 85}, {13, 13, 86}, {14, 65535, 85}, },
            {{48, 57, 87}, {69, 101, -16}, },
            {{46, 101, -16}, },
            {{43, 43, 88}, {45, 45, 88}, {48, 57, 89}, },
            {},
            {},
            {},
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 95, -21}, {97, 113, 55}, {114, 114, 90}, {115, 122, 55}, },
            {{48, 95, -21}, {97, 102, 55}, {103, 103, 91}, {104, 120, 55}, {121, 121, 92}, {122, 122, 55}, },
            {{48, 107, -27}, {108, 108, 93}, {109, 122, 55}, },
            {{48, 95, -21}, {97, 97, 94}, {98, 122, 55}, },
            {{48, 115, -22}, {116, 116, 95}, {117, 122, 55}, },
            {{48, 110, -35}, {111, 111, 96}, {112, 122, 55}, },
            {{48, 95, -21}, {97, 97, 55}, {98, 98, 97}, {99, 122, 55}, },
            {{48, 95, -21}, {97, 106, 55}, {107, 107, 98}, {108, 122, 55}, },
            {{32, 32, 99}, {48, 107, -27}, {108, 108, 100}, {109, 122, 55}, },
            {{48, 95, -21}, {97, 114, 55}, {115, 115, 101}, {116, 122, 55}, },
            {{48, 104, -26}, {105, 105, 102}, {106, 122, 55}, },
            {{48, 106, -65}, {107, 107, 103}, {108, 122, 55}, },
            {{48, 116, -34}, {117, 117, 104}, {118, 122, 55}, },
            {{48, 104, -26}, {105, 105, 105}, {106, 122, 55}, },
            {{48, 97, -64}, {98, 98, 106}, {99, 113, 55}, {114, 114, 107}, {115, 122, 55}, },
            {{48, 100, -32}, {101, 101, 108}, {102, 122, 55}, },
            {{48, 113, -58}, {114, 114, 109}, {115, 122, 55}, },
            {{48, 107, -27}, {108, 108, 110}, {109, 122, 55}, },
            {{48, 109, -25}, {110, 110, 111}, {111, 122, 55}, },
            {{48, 95, -21}, {97, 97, 112}, {98, 103, 55}, {104, 104, 113}, {105, 113, 55}, {114, 114, 114}, {115, 122, 55}, },
            {{48, 109, -25}, {110, 110, 115}, {111, 122, 55}, },
            {{48, 106, -65}, {107, 107, 116}, {108, 122, 55}, },
            {{48, 115, -22}, {116, 116, 117}, {117, 122, 55}, },
            {{48, 95, -21}, {97, 97, 118}, {98, 122, 55}, },
            {{48, 113, -58}, {114, 114, 119}, {115, 122, 55}, },
            {{48, 95, -21}, {97, 99, 55}, {100, 100, 120}, {101, 122, 55}, },
            {{48, 99, -83}, {100, 100, 121}, {101, 122, 55}, },
            {{0, 65535, -46}, },
            {{0, 41, 122}, {43, 46, 122}, {47, 47, 123}, {48, 65535, 122}, },
            {{0, 65535, -47}, },
            {},
            {{48, 101, -48}, },
            {{48, 57, 89}, },
            {{48, 57, 89}, },
            {{48, 104, -26}, {105, 105, 124}, {106, 122, 55}, },
            {{48, 106, -65}, {107, 107, 125}, {108, 122, 55}, },
            {{48, 95, -21}, {97, 97, 126}, {98, 122, 55}, },
            {{48, 95, -21}, {97, 97, 127}, {98, 122, 55}, },
            {{48, 114, -67}, {115, 115, 128}, {116, 122, 55}, },
            {{48, 104, -26}, {105, 105, 129}, {106, 122, 55}, },
            {{48, 95, -21}, {97, 97, 130}, {98, 115, 55}, {116, 116, 131}, {117, 122, 55}, },
            {{32, 32, 132}, {48, 122, -21}, },
            {{48, 95, -21}, {97, 97, 133}, {98, 122, 55}, },
            {{108, 108, 134}, },
            {{48, 95, -21}, {97, 97, 135}, {98, 122, 55}, },
            {{48, 110, -35}, {111, 111, 136}, {112, 122, 55}, },
            {{48, 109, -25}, {110, 110, 137}, {111, 122, 55}, },
            {{48, 95, -21}, {97, 103, 55}, {104, 104, 138}, {105, 122, 55}, },
            {{48, 113, -58}, {114, 114, 139}, {115, 122, 55}, },
            {{48, 109, -25}, {110, 110, 140}, {111, 122, 55}, },
            {{48, 107, -27}, {108, 108, 141}, {109, 122, 55}, },
            {{48, 109, -25}, {110, 110, 142}, {111, 122, 55}, },
            {{48, 106, -65}, {107, 107, 143}, {108, 122, 55}, },
            {{48, 95, -21}, {97, 117, 55}, {118, 118, 144}, {119, 122, 55}, },
            {{48, 95, -21}, {97, 97, 145}, {98, 122, 55}, },
            {{48, 110, -35}, {111, 111, 146}, {112, 122, 55}, },
            {{48, 115, -22}, {116, 116, 147}, {117, 122, 55}, },
            {{48, 104, -26}, {105, 105, 148}, {106, 122, 55}, },
            {{48, 104, -26}, {105, 105, 149}, {106, 122, 55}, },
            {{48, 115, -22}, {116, 116, 150}, {117, 122, 55}, },
            {{48, 114, -67}, {115, 115, 151}, {116, 122, 55}, },
            {{48, 116, -34}, {117, 117, 152}, {118, 122, 55}, },
            {{48, 95, -21}, {97, 108, 55}, {109, 109, 153}, {110, 122, 55}, },
            {{48, 102, -59}, {103, 103, 154}, {104, 122, 55}, },
            {{48, 100, -32}, {101, 101, 155}, {102, 122, 55}, },
            {{48, 104, -26}, {105, 105, 156}, {106, 122, 55}, },
            {{0, 41, 157}, {42, 42, 158}, {43, 65535, 157}, },
            {},
            {{48, 109, -25}, {110, 110, 159}, {111, 122, 55}, },
            {{48, 95, -21}, {97, 97, 160}, {98, 122, 55}, },
            {{48, 115, -22}, {116, 116, 161}, {117, 122, 55}, },
            {{48, 109, -25}, {110, 110, 162}, {111, 122, 55}, },
            {{48, 114, -67}, {115, 115, 163}, {116, 122, 55}, },
            {{48, 100, -32}, {101, 101, 164}, {102, 122, 55}, },
            {{48, 115, -22}, {116, 116, 165}, {117, 122, 55}, },
            {{48, 115, -22}, {116, 116, 166}, {117, 122, 55}, },
            {{116, 116, 167}, },
            {{48, 122, -21}, },
            {{105, 105, 168}, },
            {{48, 114, -67}, {115, 115, 169}, {116, 122, 55}, },
            {{48, 109, -25}, {110, 110, 170}, {111, 122, 55}, },
            {{48, 122, -21}, },
            {{48, 95, -21}, {97, 120, 55}, {121, 121, 171}, {122, 122, 55}, },
            {{48, 122, -21}, },
            {{48, 95, -21}, {97, 98, 55}, {99, 99, 172}, {100, 122, 55}, },
            {{48, 104, -26}, {105, 105, 173}, {106, 122, 55}, },
            {{48, 95, -21}, {97, 97, 174}, {98, 122, 55}, },
            {{48, 115, -22}, {116, 116, 175}, {117, 122, 55}, },
            {{48, 95, -21}, {97, 97, 176}, {98, 122, 55}, },
            {{48, 108, -120}, {109, 109, 177}, {110, 122, 55}, },
            {{48, 109, -25}, {110, 110, 178}, {111, 122, 55}, },
            {{48, 104, -26}, {105, 105, 179}, {106, 122, 55}, },
            {{48, 113, -58}, {114, 114, 180}, {115, 122, 55}, },
            {{48, 109, -25}, {110, 110, 181}, {111, 122, 55}, },
            {{48, 90, -21}, {95, 95, 182}, {97, 122, 55}, },
            {{48, 122, -21}, },
            {{48, 106, -65}, {107, 107, 183}, {108, 122, 55}, },
            {{48, 95, -21}, {97, 97, 184}, {98, 122, 55}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{0, 65535, -124}, },
            {{0, 41, 122}, {42, 42, 158}, {43, 65535, -86}, },
            {{48, 102, -59}, {103, 103, 185}, {104, 122, 55}, },
            {{48, 122, -21}, },
            {{48, 103, -105}, {104, 104, 186}, {105, 122, 55}, },
            {{48, 102, -59}, {103, 103, 187}, {104, 122, 55}, },
            {{48, 100, -32}, {101, 101, 188}, {102, 122, 55}, },
            {{48, 113, -58}, {114, 114, 189}, {115, 122, 55}, },
            {{48, 122, -21}, },
            {{48, 95, -21}, {97, 97, 190}, {98, 122, 55}, },
            {{97, 97, 191}, },
            {{121, 121, 192}, },
            {{48, 122, -21}, },
            {{48, 102, -59}, {103, 103, 193}, {104, 122, 55}, },
            {{48, 95, -21}, {97, 97, 194}, {98, 122, 55}, },
            {{48, 104, -26}, {105, 105, 195}, {106, 122, 55}, },
            {{48, 98, -142}, {99, 99, 196}, {100, 106, 55}, {107, 107, 197}, {108, 122, 55}, },
            {{48, 109, -25}, {110, 110, 198}, {111, 122, 55}, },
            {{48, 122, -21}, },
            {{48, 95, -21}, {97, 105, 55}, {106, 106, 199}, {107, 122, 55}, },
            {{48, 95, -21}, {97, 97, 200}, {98, 122, 55}, },
            {{48, 122, -21}, },
            {{48, 106, -65}, {107, 107, 201}, {108, 112, 55}, {113, 113, 202}, {114, 122, 55}, },
            {{48, 122, -21}, },
            {{48, 102, -59}, {103, 103, 203}, {104, 122, 55}, },
            {{48, 95, -21}, {97, 112, 55}, {113, 113, 204}, {114, 122, 55}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 95, -21}, {97, 97, 205}, {98, 122, 55}, },
            {{48, 95, -21}, {97, 97, 206}, {98, 122, 55}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 109, -25}, {110, 110, 207}, {111, 122, 55}, },
            {{107, 107, 208}, },
            {{101, 101, 209}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 95, -21}, {97, 111, 55}, {112, 112, 210}, {113, 122, 55}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 106, -65}, {107, 107, 211}, {108, 122, 55}, },
            {{48, 95, -21}, {97, 97, 212}, {98, 122, 55}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 116, -34}, {117, 117, 213}, {118, 122, 55}, },
            {{48, 122, -21}, },
            {{48, 116, -34}, {117, 117, 214}, {118, 122, 55}, },
            {{48, 122, -21}, },
            {{48, 109, -25}, {110, 110, 215}, {111, 122, 55}, },
            {{48, 115, -22}, {116, 116, 216}, {117, 122, 55}, },
            {},
            {},
            {{48, 95, -21}, {97, 97, 217}, {98, 122, 55}, },
            {{48, 122, -21}, },
            {{48, 109, -25}, {110, 110, 218}, {111, 122, 55}, },
            {{48, 100, -32}, {101, 101, 219}, {102, 122, 55}, },
            {{48, 100, -32}, {101, 101, 220}, {102, 122, 55}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 107, -27}, {108, 108, 221}, {109, 122, 55}, },
            {{48, 104, -26}, {105, 105, 222}, {106, 122, 55}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 106, -65}, {107, 107, 223}, {108, 122, 55}, },
            {{48, 122, -21}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 31, 2, 2, 2, 31, 21, 22, 19, 17, 27, 18, 31, 20, 30, 28, 16, 15, 16, 29, 29, 25, 26, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 23, 24, 16, 30, -1, -1, 30, 30, -1, 16, 16, 16, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 13, 29, 29, 29, 29, 29, 29, 29, 29, -1, -1, -1, 0, 30, -1, 30, 29, 29, 29, 29, 29, 29, 29, 29, 29, -1, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, -1, 1, 29, 29, 29, 29, 29, 29, 29, 29, -1, 13, -1, 29, 29, 14, 29, 11, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 8, 29, 29, 3, 6, 13, -1, -1, 29, 10, 29, 29, 29, 29, 10, 29, -1, -1, 3, 29, 29, 29, 29, 29, 6, 29, 29, 14, 29, 5, 29, 29, 11, 7, 8, 29, 29, 3, 9, 29, -1, -1, 6, 7, 29, 4, 4, 29, 29, 12, 5, 29, 8, 29, 14, 29, 29, 12, 11, 29, 9, 29, 29, 29, 9, 10, 29, 29, 5, 12, 7, 29, 4, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(int id)
        {
            this.id = id;
        }

        public int id()
        {
            return id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
